name: stockmanagent-p

on: 
  push:
    branches: 
      - master
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout_code
      uses: actions/checkout@v1

    - name: Preparation
      env:
        NUMBER: ${{ github.run_number }}
      run: |
        rm build.sh
        curl -o .env https://raw.githubusercontent.com/OpenLMIS/openlmis-ref-distro/master/settings-sample.env
        echo  '#!/bin/bash' >> build.sh
        echo gradle clean build >> build.sh
        chmod +x build.sh && cat build.sh
        cat .env | grep MAIL
        sed -i '/MAIL/d' .env
        sed -i '/spring_profiles/d' .env
        echo "MAIL_HOST=smtp.gmail.com" >> .env
        echo "MAIL_PORT=465" >> .env
        echo "MAIL_USERNAME=tw.siglus.dev@gmail.com" >> .env
        echo "MAIL_PASSWORD=478F9}}b9x8y75As" >> .env
        echo "MAIL_ADDRESS=tw.siglus.dev@gmail.com" >> .env
        echo "spring_profiles_active=production" >> .env
        echo "***********************"
        cat .env | grep MAIL

    - name: Login_repo
      run: |
        hostname
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 

    - name: Build_app
      run: |
        echo ">>> openlims 方法 <<<"
        docker-compose -f docker-compose.builder.yml run builder

    - name: Build_image
      run: |
        echo ">>> openlims 方法 <<<"
        docker-compose -f docker-compose.builder.yml build image
        docker images
